### ISSUE TITLE
Consider using TypeCache for better performance than assembly scanning

### ISSUE THREAD

**Issue by shanecelis** [Hibzz-Games/com.hibzz.definemanager#5]
Looks like a cool project. I like how third-party projects can opt-in to it. 

I noticed that you scan through all the assemblies, but I couldn't determine how often that happens. Every domain reload? Every enter play? If scanning assemblies happens on play or reload, I strongly suggest taking a look at [TypeCache](https://docs.unity3d.com/ScriptReference/TypeCache.html). I used [a project](https://github.com/joshcamas/unity-domain-reload-helper/pull/9) that consumed 5 seconds scanning through assemblies. When I switched it to use TypeCache, it took 50 milliseconds.

This change would probably require using an attribute rather than method name.

**Comment by sliptrixx** [comment]
Wow! Thanks for bringing this up. I wasn't aware of TypeCache and it sounds interesting (and a lot more simple). I'll try to implement it as soon as I can.

To answer your other question, it performs the reload only when the window is first opened and whenever the refresh button is pressed later on. But this will definitely help simplify things.

**Comment by sliptrixx** [comment]
Implemented the suggestion. Will keep the PR up for another few hours before merging it with the main branch.
